services:
  postgres:
    image: postgres:latest
    container_name: postgres_${DATABASE_DATABASE}
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      TZ: 'America/Sao_Paulo'
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    expose:
      - '${DATABASE_PORT}'

